[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_crowdfunding = "GAiTsjthEZq2r35wZ7nV7SsjdJbEwEDEwHx1x9ug8WjG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
